remote_theme: mikearnaldi/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  '@effect/match on GitHub':
    - 'https://github.com/effect-ts/match'